import Collatz.ReturnDefectTransport
namespace CollatzFinal.SourceProduct
#check dyadic_sum_unequal
#check dyadic_equal_sum_even
#check fixed_centre_exhaustion
#check Int.mul_eq_mul_left_iff
#check Int.eq_of_mul_eq_mul_left
#check Int.pow_pos
#check Int.pow_ne_zero
#check Int.natAbs_ofNat
#check Int.natAbs_neg
#check Int.natAbs_eq
#check Int.natAbs_pos
#check Int.natCast_ofNat
#check Int.mul_emod
#check Int.add_emod
#check Int.pow_add
#check Int.pow_succ
end CollatzFinal.SourceProduct
