import Collatz.ThreeQuarterCoalescence

namespace CollatzFinal
namespace SourceProduct

/-- The actual high-odd context used by the closeout is prefix-live:
the coefficient has survived at every earlier depth, not merely at the
current endpoint. -/
def PrefixCoefficientSurvival (n k : Nat) : Prop :=
  ∀ i, i ≤ k → CoefficientSurvives n i

/-- Consequence-pruned high-odd constructor capability. -/
def PrefixHighOddConstructorCoverage : Prop :=
  ∀ n k, 1 < n → PrefixCoefficientSurvival n k →
    n ≤ oddCount n k →
    ∃ j, OrdinaryExit n (iter shortcut (k + j) n)

theorem first_crossing_prefix_survival
    {n k : Nat}
    (hfirst : FirstCoefficientCrossingAt n (k + 1)) :
    PrefixCoefficientSurvival n k := by
  intro i hi
  unfold CoefficientSurvives coefficientDenominator coefficientNumerator
  exact first_crossing_previous_survival_bound hfirst i
    (Nat.lt_succ_of_le hi)

theorem eternal_prefix_survival
    {n k : Nat}
    (hsurv : EternalCoefficientSurvival n) :
    PrefixCoefficientSurvival n k := by
  intro i hi
  exact hsurv i

/-- Final closeout with the exact high-odd context actually generated by
minimal-bad branching. This is strictly weaker than the previous
HighOddConstructorCoverage interface. -/
theorem reaches_one_of_prefix_high_odd_and_three_quarter_coalescence7
    (hHigh : PrefixHighOddConstructorCoverage)
    (h34 : ThreeQuarterCoalescence7) :
    ∀ n, 0 < n → ∃ t, iter shortcut t n = 1 := by
  have hnone : ∀ n, ¬ PositiveBad n := by
    apply no_bad_of_no_minimal PositiveBad
    intro n hmin
    have hgt : 1 < n := by
      have hn : 0 < n := hmin.1.1
      have hne : n ≠ 1 := by
        intro heq
        apply hmin.1.2
        subst n
        exact ⟨0, by simp [iter, Terminal]⟩
      omega
    rcases coefficient_survival_or_first_crossing n with hsurv | ⟨d, hfirst⟩
    · obtain ⟨hs, hq⟩ :=
        eternal_survival_enters_high_odd hmin.1.1 hsurv
      have hpref : PrefixCoefficientSurvival n (2 * n) :=
        eternal_prefix_survival hsurv
      obtain ⟨j, hexit⟩ := hHigh n (2 * n) hgt hpref hq
      exact minimal_bad_has_no_ordinary_exit hmin (2 * n + j) hexit
    · cases d with
      | zero =>
          have hc : CoefficientCrossingAt n 0 := hfirst.1
          unfold CoefficientCrossingAt at hc
          simp at hc
      | succ k =>
          have hhard : HardFirstCrossing n k :=
            minimal_bad_first_crossing_is_hard hmin hfirst
          rcases minimal_bad_first_crossing_constructor_domains
            hmin hfirst with ⟨_, horigin | hlarge⟩
          · have heven := hard_first_crossing_last_step_even hhard
            have hqeq :
                oddCount n (k + 1) = oddCount n k := by
              simp [oddCount, heven]
            have hpref : PrefixCoefficientSurvival n k :=
              first_crossing_prefix_survival hfirst
            have hqK : n ≤ oddCount n k := by
              simpa [hqeq] using horigin
            obtain ⟨j, hexit⟩ := hHigh n k hgt hpref hqK
            exact minimal_bad_has_no_ordinary_exit hmin (k + j) hexit
          · rcases hlarge with ⟨hq, hwin, hmod⟩
            have hLarge :=
              large_crossing_coverage_of_three_quarter_coalescence7 h34
            obtain ⟨j, hexit⟩ :=
              hLarge n k hgt hhard hq hwin hmod
            exact minimal_bad_has_no_ordinary_exit hmin ((k + 1) + j) hexit
  intro n hn
  have hgood : CollatzGood n := by
    apply Classical.byContradiction
    intro hbad
    exact hnone n ⟨hn, hbad⟩
  exact collatzGood_eventually_one hgood

#print axioms reaches_one_of_prefix_high_odd_and_three_quarter_coalescence7

end SourceProduct
end CollatzFinal
