import Collatz.FourThirdsAdmission
import Collatz.OwnerBoundarySplit

namespace CollatzFinal
namespace SourceProduct

/-- In the V17 deficit-one normalized-core interval, source classes 3 or 7
modulo 8 sharpen p < 2*n to the consequence-maximal endpoint p <= 2*n-3.
The excluded value 2*n-1 is exactly 5 modulo 8. -/
theorem normalized_odd_endpoint_add_three_le_double
    {n p : Nat}
    (hgt : 1 < n)
    (hn8 : n % 8 = 3 ∨ n % 8 = 7)
    (hpn : n ≤ p)
    (hplt : p < 2 * n)
    (hpodd : p % 2 = 1)
    (hp5 : p % 8 ≠ 5) :
    p + 3 ≤ 2 * n := by
  rcases hn8 with hn8 | hn8 <;> omega

/-- Exact affine exclusion interface for the deficit-one branch.

This is deliberately the semantic statement V18/V19 are discovering:
no allowed normalized odd endpoint can satisfy the actual source-coupled affine
identity at a four-thirds deficit-one boundary.  It is a premise, not promoted
from bounded Crystal evidence. -/
def FourThirdsDeficitAffineExclusion : Prop :=
  ∀ n k p,
    1 < n →
    (n % 8 = 3 ∨ n % 8 = 7) →
    oddCount n k = (4 * n) / 3 →
    oddCount n k + 1 = qmin k →
    n ≤ p →
    p + 3 ≤ 2 * n →
    p % 2 = 1 →
    p % 8 ≠ 5 →
    2 ^ k * p ≠ 3 ^ oddCount n k * n + bias n k

/-- The independently open coefficient-survival half of the V17 odd boundary
split.  Minimal-bad context is explicit because this is the exact context in
which the closeout consumes the premise. -/
def FourThirdsSurvivalOddExclusion : Prop :=
  ∀ n k,
    MinimalBad PositiveBad n →
    oddCount n k = (4 * n) / 3 →
    qmin k ≤ oddCount n k →
    iter shortcut k n % 2 = 1 →
    False

/-- The deficit affine exclusion removes the deficit-one side of the odd
four-thirds boundary for a hypothetical minimal bad source. -/
theorem minimal_bad_no_four_thirds_deficit_odd
    (hDef : FourThirdsDeficitAffineExclusion)
    {n k : Nat}
    (hmin : MinimalBad PositiveBad n)
    (hq : oddCount n k = (4 * n) / 3)
    (hodd : iter shortcut k n % 2 = 1)
    (hdef : oddCount n k + 1 = qmin k) :
    False := by
  have hgt : 1 < n := by
    have hn : 0 < n := hmin.1.1
    have hne : n ≠ 1 := by
      intro heq
      apply hmin.1.2
      subst n
      exact ⟨0, by simp [iter, Terminal]⟩
    omega
  have hn8 := minimal_bad_source_mod8_three_or_seven hmin
  obtain ⟨p, hpn, hplt, _hppos, hpodd, hp5, heq⟩ :=
    minimal_bad_four_thirds_deficit_one_normalized_core
      hmin hq hodd hdef
  have hpmax :
      p + 3 ≤ 2 * n :=
    normalized_odd_endpoint_add_three_le_double
      hgt hn8 hpn hplt hpodd hp5
  have hneq :=
    hDef n k p hgt hn8 hq hdef hpn hpmax hpodd hp5
  have haff := exact_affine n k
  rw [heq] at haff
  exact hneq haff

/-- Exact two-premise closeout generated by the V17 boundary split.

No later trajectory search is used.  V13 supplies a first transition through
q=floor(4n/3); that transition is odd.  The persistent corridor says the
predecessor is either coefficient-surviving or exact deficit one.  Excluding
those two source-admission cases therefore eliminates every minimal bad source.
-/
theorem reaches_one_of_four_thirds_affine_and_survival_exclusion
    (hDef : FourThirdsDeficitAffineExclusion)
    (hSurv : FourThirdsSurvivalOddExclusion) :
    ∀ n, 0 < n → ∃ t, iter shortcut t n = 1 := by
  have hnone : ∀ n, ¬ PositiveBad n := by
    apply no_bad_of_no_minimal PositiveBad
    intro n hmin
    have hgt : 1 < n := by
      have hn : 0 < n := hmin.1.1
      have hne : n ≠ 1 := by
        intro heq
        apply hmin.1.2
        subst n
        exact ⟨0, by simp [iter, Terminal]⟩
      omega
    let Q := (4 * n) / 3
    have hQlt : Q < 2 * n := by
      dsimp [Q]
      exact four_thirds_floor_lt_double hgt
    have hstrict :
        2 * n < oddCount n (4 * n) :=
      minimal_bad_quadruple_depth_strict_double_diagonal hmin
    have hQfinal : Q < oddCount n (4 * n) := by omega
    obtain ⟨k, _hklt, hq, hqs⟩ :=
      oddCount_exact_boundary (n := n) (Q := Q)
        (K := 4 * n) hQfinal
    have hoddne :
        iter shortcut k n % 2 ≠ 0 := by
      intro he
      have hs : oddCount n (k + 1) = oddCount n k := by
        simp [oddCount, he]
      omega
    have hodd :
        iter shortcut k n % 2 = 1 := by
      have hm := Nat.mod_lt (iter shortcut k n) (by decide : 0 < 2)
      omega
    have hq' :
        oddCount n k = (4 * n) / 3 := by
      simpa [Q] using hq
    have hn : 0 < n := hmin.1.1
    have hqpos : 0 < oddCount n k := by
      rw [hq']
      have hl := source_le_four_thirds_floor hn
      omega
    have hq2 : oddCount n k ≤ 2 * n := by
      rw [hq']
      exact Nat.le_of_lt (four_thirds_floor_lt_double hgt)
    rcases minimal_bad_persistent_survival_or_deficit_one
      hmin hqpos hq2 with hsurv | hdef
    · exact hSurv n k hmin hq' hsurv hodd
    · exact minimal_bad_no_four_thirds_deficit_odd
        hDef hmin hq' hodd hdef
  intro n hn
  have hgood : CollatzGood n := by
    apply Classical.byContradiction
    intro hbad
    exact hnone n ⟨hn, hbad⟩
  exact collatzGood_eventually_one hgood

#print axioms normalized_odd_endpoint_add_three_le_double
#print axioms minimal_bad_no_four_thirds_deficit_odd
#print axioms reaches_one_of_four_thirds_affine_and_survival_exclusion

end SourceProduct
end CollatzFinal
