import Std

universe u

namespace EvidenceGeneratesInterventionOntology

/-- Accepted finite verifier evidence. -/
structure Evidence (α : Type u) where
  args : List α

/-- The evidence itself generates one anonymous candidate intervention per
    position; there is no externally enumerated intervention carrier. -/
abbrev CandidateIntervention {α : Type u} (e : Evidence α) := Fin e.args.length

/-- Fixed structural intervention grammar: delete exactly the chosen evidence
    position. -/
def deleteAt {α : Type u} (xs : List α) (p : Fin xs.length) : List α :=
  xs.take p.val ++ xs.drop (p.val + 1)

/-- Verifier response to the intervention generated by one evidence position. -/
def response {α : Type u} (V : List α → Bool) (e : Evidence α)
    (p : CandidateIntervention e) : Bool :=
  V (deleteAt e.args p)

/-- Two generated interventions have the same identity exactly when their
    verifier-visible consequences agree. -/
def InterventionEq {α : Type u} (V : List α → Bool) (e : Evidence α)
    (p q : CandidateIntervention e) : Prop :=
  response V e p = response V e q

/-- This equality is automatically an equivalence relation because it is the
    kernel of the verifier consequence. -/
def interventionSetoid {α : Type u} (V : List α → Bool) (e : Evidence α) :
    Setoid (CandidateIntervention e) where
  r := InterventionEq V e
  iseqv := by
    constructor
    · intro p; rfl
    · intro p q h; exact h.symm
    · intro p q r hpq hqr; exact hpq.trans hqr

/-- Ontology of interventions generated from evidence positions and quotiented
    by verifier consequence. -/
def InterventionOntology {α : Type u} (V : List α → Bool) (e : Evidence α) :=
  Quotient (interventionSetoid V e)

def code {α : Type u} (V : List α → Bool) (e : Evidence α) :
    CandidateIntervention e → InterventionOntology V e :=
  fun p => Quotient.mk (interventionSetoid V e) p

 theorem same_response_collapses
    {α : Type u} (V : List α → Bool) (e : Evidence α)
    {p q : CandidateIntervention e}
    (h : response V e p = response V e q) :
    code V e p = code V e q := by
  exact Quotient.sound h

 theorem different_response_forces_distinct_interventions
    {α : Type u} (V : List α → Bool) (e : Evidence α)
    {p q : CandidateIntervention e}
    (h : response V e p ≠ response V e q) :
    code V e p ≠ code V e q := by
  intro heq
  exact h (Quotient.exact heq)

/-- A causal residual is generated when exactly one evidence-generated deletion
    flips the verifier to rejection. -/
def UniqueRejectingIntervention
    {α : Type u} (V : List α → Bool) (e : Evidence α) : Prop :=
  ∃! p : CandidateIntervention e, response V e p = false

noncomputable def selectedIntervention
    {α : Type u} {V : List α → Bool} {e : Evidence α}
    (h : UniqueRejectingIntervention V e) : CandidateIntervention e :=
  Classical.choose h

 theorem selected_intervention_is_verifier_rejecting
    {α : Type u} {V : List α → Bool} {e : Evidence α}
    (h : UniqueRejectingIntervention V e) :
    response V e (selectedIntervention h) = false := by
  exact (Classical.choose_spec h).1

/-- If all intervention responses are erased to the same value, the quotient
    collapses every generated intervention. -/
def erasedVerifier {α : Type u} : List α → Bool := fun _ => true

theorem erasure_collapses_generated_interventions
    {α : Type u} (e : Evidence α) (p q : CandidateIntervention e) :
    code (erasedVerifier (α := α)) e p = code erasedVerifier e q := by
  exact Quotient.sound rfl

/-- Concrete witness with no intervention labels: the two candidate experiments
    are simply the two positions of the accepted trace. -/
def pairEvidence : Evidence Bool := ⟨[false, true]⟩

def pairVerifier : List Bool → Bool
  | [false, true] => true
  | [true] => false
  | [false] => true
  | _ => false

def pos0 : CandidateIntervention pairEvidence := ⟨0, by decide⟩
def pos1 : CandidateIntervention pairEvidence := ⟨1, by decide⟩

theorem pair_interventions_are_verifier_distinct :
    code pairVerifier pairEvidence pos0 ≠ code pairVerifier pairEvidence pos1 := by
  apply different_response_forces_distinct_interventions
  decide

 theorem pair_has_unique_rejecting_intervention :
    UniqueRejectingIntervention pairVerifier pairEvidence := by
  refine ⟨pos0, by decide, ?_⟩
  intro p hp
  apply Fin.ext
  have hlt : p.val < 2 := p.isLt
  interval_cases p.val <;> simp [response, deleteAt, pairVerifier, pos0, pos1] at hp ⊢

/-- End-to-end result: evidence generates the experiment candidates, verifier
    consequence generates their ontology, and a unique counterfactual failure
    selects one anonymous intervention as the residual-bearing experiment.

    No source/target/left/right/intervention enum is supplied.  The remaining
    scaffold is the finite ordered-list evidence grammar and the delete-one
    constructor itself. -/
theorem evidence_generates_verifier_selected_intervention_ontology :
    code pairVerifier pairEvidence pos0 ≠ code pairVerifier pairEvidence pos1 ∧
    ∃ h : UniqueRejectingIntervention pairVerifier pairEvidence,
      response pairVerifier pairEvidence (selectedIntervention h) = false := by
  exact ⟨pair_interventions_are_verifier_distinct,
    ⟨pair_has_unique_rejecting_intervention,
      selected_intervention_is_verifier_rejecting pair_has_unique_rejecting_intervention⟩⟩

#check same_response_collapses
#check different_response_forces_distinct_interventions
#check selected_intervention_is_verifier_rejecting
#check erasure_collapses_generated_interventions
#check pair_interventions_are_verifier_distinct
#check pair_has_unique_rejecting_intervention
#check evidence_generates_verifier_selected_intervention_ontology

end EvidenceGeneratesInterventionOntology
