import MultiSourceTwistLayer
import FunnelCore
import Mathlib.Tactic

namespace AC

/-- The set of relators other than coordinate i. -/
def otherRelatorSet {n : ℕ} (R : Relators n) (i : Fin n) : Set (Word n) :=
  {b | ∃ j : Fin n, j ≠ i ∧ R j = b}

/-- The normal closure generated by all relators except coordinate i. -/
def otherRelatorNormalClosure {n : ℕ} (R : Relators n) (i : Fin n) :
    Subgroup (Word n) :=
  sourceNormalClosure (otherRelatorSet R i)

/-- A single removable twist from another relator can be inserted into
coordinate i while all other coordinates are restored exactly. -/
theorem coordinate_twist_insert_reachable {n : ℕ}
    (R : Relators n) (i j : Fin n) (hij : i ≠ j)
    (a w : Word n) :
    Reachable
      (Function.update R i a)
      (Function.update R i ((R j)⁻¹ * w * R j * w⁻¹ * a)) := by
  let P : Relators n := Function.update R i a
  have hraw :=
    reachable_symm (commutatorTwist_contract P i j hij w)
  simpa [P, hij, Ne.symm hij] using hraw

/-- Every element of the multi-source twist layer can be absorbed into one
coordinate by an ordinary AC path, with all other relators restored. -/
theorem sourceTwistLayer_coordinate_reachable {n : ℕ}
    (R : Relators n) (i : Fin n) {h : Word n}
    (hh : h ∈ sourceTwistLayer (otherRelatorSet R i))
    (a : Word n) :
    Reachable
      (Function.update R i a)
      (Function.update R i (h * a)) := by
  unfold sourceTwistLayer at hh
  induction hh using Subgroup.closure_induction generalizing a with
  | mem x hx =>
      rcases hx with ⟨b, hb, w, rfl⟩
      rcases hb with ⟨j, hji, hjb⟩
      subst b
      exact coordinate_twist_insert_reachable R i j (Ne.symm hji) a w
  | one =>
      simpa using
        (Relation.ReflTransGen.refl :
          Reachable (Function.update R i a) (Function.update R i a))
  | mul x y hx hy ihx ihy =>
      have p1 :
          Reachable
            (Function.update R i a)
            (Function.update R i (y * a)) :=
        ihy a
      have p2 :
          Reachable
            (Function.update R i (y * a))
            (Function.update R i (x * (y * a))) :=
        ihx (y * a)
      have p := p1.trans p2
      simpa [mul_assoc] using p
  | inv x hx ih =>
      have p :
          Reachable
            (Function.update R i (x⁻¹ * a))
            (Function.update R i (x * (x⁻¹ * a))) :=
        ih (x⁻¹ * a)
      have p' :
          Reachable
            (Function.update R i (x⁻¹ * a))
            (Function.update R i a) := by
        simpa [mul_assoc] using p
      exact reachable_symm p'

/-- Rank-independent coordinate quotient theorem.

Let N_{-i} be the normal closure of every relator except R_i.  Any element of
[N_{-i}, F] can be left-multiplied into R_i by ordinary AC moves while all
other relators return unchanged.
-/
theorem otherRelatorCommutator_coordinate_reachable {n : ℕ}
    (R : Relators n) (i : Fin n) {h : Word n}
    (hh :
      h ∈ ⁅otherRelatorNormalClosure R i, (⊤ : Subgroup (Word n))⁆) :
    Reachable R (Function.update R i (h * R i)) := by
  have htw :
      h ∈ sourceTwistLayer (otherRelatorSet R i) := by
    rw [sourceTwistLayer_eq_commutatorLayer]
    exact hh
  have p :=
    sourceTwistLayer_coordinate_reachable R i htw (R i)
  simpa [otherRelatorNormalClosure] using p

/-- Therefore a commutator-layer coordinate change preserves every future
ordinary-AC reachability consequence. -/
theorem otherRelatorCommutator_target_iff {n : ℕ}
    (R T : Relators n) (i : Fin n) {h : Word n}
    (hh :
      h ∈ ⁅otherRelatorNormalClosure R i, (⊤ : Subgroup (Word n))⁆) :
    Reachable R T ↔
      Reachable (Function.update R i (h * R i)) T := by
  exact reachable_target_iff_of_reachable
    (otherRelatorCommutator_coordinate_reachable R i hh)

end AC
