import ReachabilityEquivalence
import Mathlib.Tactic

/-!
# M-transformations inside the official Andrews--Curtis semantics

A classical compression of Andrews--Curtis moves is the M-transformation:
replace one relator by itself times an arbitrary element of the normal closure
of the *other* relators.

This file proves the constructive direction directly from the official
`AC.Step` relation.
-/

namespace AC

/-- The set of relators other than coordinate `i`. -/
def otherRelators {n : ℕ} (R : Relators n) (i : Fin n) : Set (Word n) :=
  {u | ∃ j : Fin n, j ≠ i ∧ u = R j}

/-- Right multiplication by an arbitrary conjugate of another relator is
AC-reachable while restoring that other relator exactly. -/
theorem rightMulConjugate_reachable {n : ℕ} (R : Relators n)
    (i j : Fin n) (hji : j ≠ i) (a c : Word n) :
    Reachable
      (Function.update R i a)
      (Function.update R i (a * (c * R j * c⁻¹))) := by
  let S0 : Relators n := Function.update R i a
  let S1 : Relators n := Function.update S0 j (c * S0 j * c⁻¹)
  let S2 : Relators n := Function.update S1 i (S1 i * S1 j)
  let S3 : Relators n := Function.update S2 j (c⁻¹ * S2 j * (c⁻¹)⁻¹)

  have hs1 : Step S0 S1 := by
    simpa [S1] using Step.conj S0 j c
  have hs2 : Step S1 S2 := by
    simpa [S2] using Step.mulRight S1 i j (Ne.symm hji)
  have hs3 : Step S2 S3 := by
    simpa [S3] using Step.conj S2 j c⁻¹

  have p1 : Reachable S0 S1 := step_reachable' hs1
  have p2 : Reachable S0 S2 := Relation.ReflTransGen.tail p1 hs2
  have p3 : Reachable S0 S3 := Relation.ReflTransGen.tail p2 hs3

  have hfinal :
      S3 = Function.update R i (a * (c * R j * c⁻¹)) := by
    funext q
    by_cases hqi : q = i
    · subst q
      simp [S0, S1, S2, S3, hji, Ne.symm hji, mul_assoc]
    · by_cases hqj : q = j
      · subst q
        simp [S0, S1, S2, S3, hji, Ne.symm hji, mul_assoc]
      · simp [S0, S1, S2, S3, hqi, hqj]
  rw [hfinal] at p3
  exact p3

/-- Strong induction form of the M-transformation theorem.

For any current value `a` at coordinate `i`, right multiplication by an
element of the normal closure generated by the other relators is AC-reachable.
-/
theorem mTransform_update_reachable {n : ℕ} (R : Relators n)
    (i : Fin n) (a u : Word n)
    (hu : u ∈ Subgroup.normalClosure (otherRelators R i)) :
    Reachable
      (Function.update R i a)
      (Function.update R i (a * u)) := by
  change u ∈ Subgroup.closure (Group.conjugatesOfSet (otherRelators R i)) at hu

  have hall :
      ∀ (x : Word n),
        x ∈ Subgroup.closure (Group.conjugatesOfSet (otherRelators R i)) →
        ∀ a : Word n,
          Reachable
            (Function.update R i a)
            (Function.update R i (a * x)) := by
    intro x hx
    induction hx using Subgroup.closure_induction with
    | mem x hx =>
        intro a
        rcases Group.mem_conjugatesOfSet_iff.1 hx with ⟨r, hr, hconj⟩
        rcases hr with ⟨j, hji, rfl⟩
        rcases isConj_iff.1 hconj with ⟨c, rfl⟩
        exact rightMulConjugate_reachable R i j hji a c

    | one =>
        intro a
        simpa using
          (Relation.ReflTransGen.refl :
            Reachable (Function.update R i a) (Function.update R i a))

    | mul x y hx hy ihx ihy =>
        intro a
        have p1 := ihx a
        have p2 := ihy (a * x)
        simpa [mul_assoc] using p1.trans p2

    | inv x hx ih =>
        intro a
        have p := ih (a * x⁻¹)
        have hcancel : (a * x⁻¹) * x = a := by group
        rw [hcancel] at p
        exact reachable_symm p

  exact hall u hu a

/-- Classical M-transformation: multiplying one relator on the right by any
element in the normal closure of all the other relators is AC-reachable. -/
theorem mTransform_reachable {n : ℕ} (R : Relators n)
    (i : Fin n) (u : Word n)
    (hu : u ∈ Subgroup.normalClosure (otherRelators R i)) :
    Reachable R (Function.update R i (R i * u)) := by
  have h := mTransform_update_reachable R i (R i) u hu
  have hsrc : Function.update R i (R i) = R := by
    funext q
    by_cases hqi : q = i
    · subst q; simp
    · simp [hqi]
  rw [hsrc] at h
  exact h

/-- Left multiplication by the same normal closure is also reachable. -/
theorem mTransform_left_reachable {n : ℕ} (R : Relators n)
    (i : Fin n) (u : Word n)
    (hu : u ∈ Subgroup.normalClosure (otherRelators R i)) :
    Reachable R (Function.update R i (u * R i)) := by
  let N := Subgroup.normalClosure (otherRelators R i)
  have hconj : (R i)⁻¹ * u * R i ∈ N := by
    exact Subgroup.Normal.conj_mem inferInstance _ hu (R i)⁻¹
  have h :=
    mTransform_reachable R i ((R i)⁻¹ * u * R i) hconj
  have heq : R i * ((R i)⁻¹ * u * R i) = u * R i := by group
  simpa [heq] using h

/-- M-transformations preserve every future reachability consequence. -/
theorem mTransform_target_iff {n : ℕ} (R : Relators n)
    (i : Fin n) (u : Word n)
    (hu : u ∈ Subgroup.normalClosure (otherRelators R i))
    (T : Relators n) :
    Reachable (Function.update R i (R i * u)) T ↔ Reachable R T := by
  have h := mTransform_reachable R i u hu
  constructor
  · intro h1
    exact (reachable_symm h).trans h1
  · intro h2
    exact h.trans h2

end AC
