import TwistGeneratedLayer
import TwistCommutatorEquality
import Mathlib.Tactic

open scoped commutatorElement

namespace AC

/-- Normal closure of an arbitrary source set of words. -/
def sourceNormalClosure {n : ℕ} (S : Set (Word n)) : Subgroup (Word n) :=
  Subgroup.normalClosure S

/-- All removable conjugacy-difference factors generated by words in S. -/
def sourceTwistFactorSet {n : ℕ} (S : Set (Word n)) : Set (Word n) :=
  {x | ∃ b ∈ S, ∃ w : Word n, b⁻¹ * w * b * w⁻¹ = x}

/-- Ordinary subgroup generated by all removable factors from all sources in S. -/
def sourceTwistLayer {n : ℕ} (S : Set (Word n)) : Subgroup (Word n) :=
  Subgroup.closure (sourceTwistFactorSet S)

/-- The multi-source twist layer is already normal. -/
theorem sourceTwistLayer_normal {n : ℕ} (S : Set (Word n)) :
    (sourceTwistLayer S).Normal := by
  constructor
  intro x hx q
  unfold sourceTwistLayer at hx ⊢
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with ⟨b, hb, w, rfl⟩
      rw [conjugate_twistFactor]
      exact (Subgroup.closure (sourceTwistFactorSet S)).mul_mem
        ((Subgroup.closure (sourceTwistFactorSet S)).inv_mem
          (Subgroup.subset_closure ⟨b, hb, q, rfl⟩))
        (Subgroup.subset_closure ⟨b, hb, q * w, rfl⟩)
  | one =>
      simp
  | mul x y hx hy ihx ihy =>
      have hmem :=
        (Subgroup.closure (sourceTwistFactorSet S)).mul_mem ihx ihy
      convert hmem using 1 <;> group
  | inv x hx ih =>
      have hmem :=
        (Subgroup.closure (sourceTwistFactorSet S)).inv_mem ih
      convert hmem using 1 <;> group

/-- Every multi-source removable factor lies in the commutator of the normal
closure of S with the ambient free group. -/
theorem sourceTwistLayer_le_commutatorLayer {n : ℕ} (S : Set (Word n)) :
    sourceTwistLayer S ≤
      ⁅sourceNormalClosure S, (⊤ : Subgroup (Word n))⁆ := by
  unfold sourceTwistLayer
  apply Subgroup.closure_le.mpr
  intro x hx
  rcases hx with ⟨b, hb, w, rfl⟩
  have hbN : b⁻¹ ∈ sourceNormalClosure S := by
    exact (sourceNormalClosure S).inv_mem (Subgroup.subset_normalClosure hb)
  have hw : w ∈ (⊤ : Subgroup (Word n)) := by simp
  rw [twistFactor_eq_commutator]
  exact Subgroup.commutator_mem_commutator hbN hw

/-- Words that commute with everything modulo the multi-source twist layer. -/
def centralModuloSources {n : ℕ} (S : Set (Word n)) : Subgroup (Word n) where
  carrier := {a | ∀ g : Word n, ⁅a, g⁆ ∈ sourceTwistLayer S}
  one_mem' := by
    intro g
    simp
  mul_mem' := by
    intro a c ha hc g
    letI : (sourceTwistLayer S).Normal := sourceTwistLayer_normal S
    rw [twist_commutator_mul_left]
    exact (sourceTwistLayer S).mul_mem
      (Subgroup.Normal.conj_mem inferInstance _ (hc g) a)
      (ha g)
  inv_mem' := by
    intro a ha g
    letI : (sourceTwistLayer S).Normal := sourceTwistLayer_normal S
    rw [twist_commutator_inv_left]
    have hga : ⁅g, a⁆ ∈ sourceTwistLayer S := by
      have hi := (sourceTwistLayer S).inv_mem (ha g)
      rw [commutatorElement_inv] at hi
      exact hi
    exact Subgroup.Normal.conj_mem' inferInstance _ hga a

theorem centralModuloSources_normal {n : ℕ} (S : Set (Word n)) :
    (centralModuloSources S).Normal := by
  constructor
  intro a ha q
  change ∀ g : Word n, ⁅q * a * q⁻¹, g⁆ ∈ sourceTwistLayer S
  change ∀ g : Word n, ⁅a, g⁆ ∈ sourceTwistLayer S at ha
  intro g
  letI : (sourceTwistLayer S).Normal := sourceTwistLayer_normal S
  have hbase :
      ⁅a, q⁻¹ * g * q⁆ ∈ sourceTwistLayer S :=
    ha (q⁻¹ * g * q)
  have hconj :
      q * ⁅a, q⁻¹ * g * q⁆ * q⁻¹ ∈ sourceTwistLayer S :=
    Subgroup.Normal.conj_mem inferInstance _ hbase q
  rw [conjugate_commutatorElement] at hconj
  simpa [mul_assoc] using hconj

/-- Every source word is central modulo the layer generated by all source
twists. -/
theorem source_mem_centralModuloSources {n : ℕ}
    (S : Set (Word n)) {b : Word n} (hb : b ∈ S) :
    b ∈ centralModuloSources S := by
  change ∀ g : Word n, ⁅b, g⁆ ∈ sourceTwistLayer S
  intro g
  letI : (sourceTwistLayer S).Normal := sourceTwistLayer_normal S
  have hdelta :
      b⁻¹ * g * b * g⁻¹ ∈ sourceTwistLayer S := by
    apply Subgroup.subset_closure
    exact ⟨b, hb, g, rfl⟩
  have hbinv : ⁅b⁻¹, g⁆ ∈ sourceTwistLayer S := by
    rw [← twistFactor_eq_commutator]
    exact hdelta
  have hgb : ⁅g, b⁆ ∈ sourceTwistLayer S := by
    have hc :
        b * ⁅b⁻¹, g⁆ * b⁻¹ ∈ sourceTwistLayer S :=
      Subgroup.Normal.conj_mem inferInstance _ hbinv b
    rw [twist_commutator_inv_left] at hc
    simpa [mul_assoc] using hc
  have hi := (sourceTwistLayer S).inv_mem hgb
  rw [commutatorElement_inv] at hi
  exact hi

theorem sourceNormalClosure_le_centralModuloSources {n : ℕ}
    (S : Set (Word n)) :
    sourceNormalClosure S ≤ centralModuloSources S := by
  letI : (centralModuloSources S).Normal :=
    centralModuloSources_normal S
  unfold sourceNormalClosure
  apply Subgroup.normalClosure_le_normal
  intro b hb
  exact source_mem_centralModuloSources S hb

theorem sourceCommutatorLayer_le_sourceTwistLayer {n : ℕ}
    (S : Set (Word n)) :
    ⁅sourceNormalClosure S, (⊤ : Subgroup (Word n))⁆ ≤
      sourceTwistLayer S := by
  rw [Subgroup.commutator_le]
  intro a ha g _hg
  have hcentral :=
    sourceNormalClosure_le_centralModuloSources S ha
  change ∀ x : Word n, ⁅a, x⁆ ∈ sourceTwistLayer S at hcentral
  exact hcentral g

/-- Exact multi-source characterization.

The subgroup generated by all removable conjugacy-difference factors from a
source set S is exactly the commutator of the normal closure of S with the
ambient free group.
-/
theorem sourceTwistLayer_eq_commutatorLayer {n : ℕ}
    (S : Set (Word n)) :
    sourceTwistLayer S =
      ⁅sourceNormalClosure S, (⊤ : Subgroup (Word n))⁆ := by
  apply le_antisymm
  · exact sourceTwistLayer_le_commutatorLayer S
  · exact sourceCommutatorLayer_le_sourceTwistLayer S

end AC
