import CoordinateQuotient
import Mathlib.Tactic

namespace AC

/-- Insert an arbitrary conjugate of a distinct relator into coordinate i,
then restore the source relator exactly. -/
theorem coordinate_conjugate_insert_reachable {n : ℕ}
    (R : Relators n) (i j : Fin n) (hij : i ≠ j)
    (a c : Word n) :
    Reachable
      (Function.update R i a)
      (Function.update R i ((c * R j * c⁻¹) * a)) := by
  let P : Relators n := Function.update R i a
  let Q : Relators n := Function.update P j (c * P j * c⁻¹)
  let M : Relators n := Function.update Q i (Q j * Q i)
  let F : Relators n := Function.update R i ((c * R j * c⁻¹) * a)

  have hs1 : Step P Q := by
    simpa [Q] using Step.conj P j c
  have p1 : Reachable P Q :=
    Relation.ReflTransGen.single hs1

  have p2raw := funnelCore_leftMul_reachable Q i j hij
  have p2 : Reachable Q M := by
    simpa [M] using p2raw

  have hs3raw :=
    Step.conj M j c⁻¹
  have htarget :
      Function.update M j (c⁻¹ * M j * (c⁻¹)⁻¹) = F := by
    funext q
    by_cases hqj : q = j
    · subst q
      simp [M, Q, P, F, hij, Ne.symm hij]
      group
    · by_cases hqi : q = i
      · subst q
        simp [M, Q, P, F, hij, Ne.symm hij]
      · simp [M, Q, P, F, hqi, hqj]
  rw [htarget] at hs3raw
  have p3 : Reachable M F :=
    Relation.ReflTransGen.single hs3raw

  have p := (p1.trans p2).trans p3
  simpa [P, F] using p

/-- General normal-closure coordinate law.

Any element in the normal closure generated by all relators except coordinate
i can be left-multiplied into coordinate i by ordinary AC moves while all
other relators are restored.
-/
theorem otherRelatorNormalClosure_coordinate_reachable_aux {n : ℕ}
    (R : Relators n) (i : Fin n) {h : Word n}
    (hh : h ∈ otherRelatorNormalClosure R i)
    (a : Word n) :
    Reachable
      (Function.update R i a)
      (Function.update R i (h * a)) := by
  unfold otherRelatorNormalClosure sourceNormalClosure at hh
  change h ∈ Subgroup.closure (Group.conjugatesOfSet (otherRelatorSet R i)) at hh
  induction hh using Subgroup.closure_induction generalizing a with
  | mem x hx =>
      rw [Group.mem_conjugatesOfSet_iff] at hx
      rcases hx with ⟨b, hb, hconj⟩
      rcases hb with ⟨j, hji, hjb⟩
      obtain ⟨c, rfl⟩ := isConj_iff.1 hconj
      subst b
      exact coordinate_conjugate_insert_reachable
        R i j (Ne.symm hji) a c
  | one =>
      simpa using
        (Relation.ReflTransGen.refl :
          Reachable (Function.update R i a) (Function.update R i a))
  | mul x y hx hy ihx ihy =>
      have p1 :
          Reachable
            (Function.update R i a)
            (Function.update R i (y * a)) :=
        ihy a
      have p2 :
          Reachable
            (Function.update R i (y * a))
            (Function.update R i (x * (y * a))) :=
        ihx (y * a)
      have p := p1.trans p2
      simpa [mul_assoc] using p
  | inv x hx ih =>
      have p :
          Reachable
            (Function.update R i (x⁻¹ * a))
            (Function.update R i (x * (x⁻¹ * a))) :=
        ih (x⁻¹ * a)
      have p' :
          Reachable
            (Function.update R i (x⁻¹ * a))
            (Function.update R i a) := by
        simpa [mul_assoc] using p
      exact reachable_symm p'

/-- Maximal coordinate quotient law used classically in AC calculations. -/
theorem otherRelatorNormalClosure_coordinate_reachable {n : ℕ}
    (R : Relators n) (i : Fin n) {h : Word n}
    (hh : h ∈ otherRelatorNormalClosure R i) :
    Reachable R (Function.update R i (h * R i)) := by
  have p :=
    otherRelatorNormalClosure_coordinate_reachable_aux R i hh (R i)
  simpa using p

/-- Congruence modulo the normal closure of the other relators preserves every
future ordinary-AC reachability consequence. -/
theorem otherRelatorNormalClosure_target_iff {n : ℕ}
    (R T : Relators n) (i : Fin n) {h : Word n}
    (hh : h ∈ otherRelatorNormalClosure R i) :
    Reachable R T ↔
      Reachable (Function.update R i (h * R i)) T := by
  exact reachable_target_iff_of_reachable
    (otherRelatorNormalClosure_coordinate_reachable R i hh)

/-- The commutator-coordinate theorem is a corollary of the stronger
normal-closure coordinate law. -/
theorem commutatorCoordinate_factors_through_normalClosure {n : ℕ}
    (R : Relators n) (i : Fin n) {h : Word n}
    (hh :
      h ∈ ⁅otherRelatorNormalClosure R i, (⊤ : Subgroup (Word n))⁆) :
    Reachable R (Function.update R i (h * R i)) := by
  letI : (otherRelatorNormalClosure R i).Normal := by
    unfold otherRelatorNormalClosure sourceNormalClosure
    infer_instance
  have hN :
      h ∈ otherRelatorNormalClosure R i :=
    Subgroup.commutator_le_left
      (otherRelatorNormalClosure R i)
      (⊤ : Subgroup (Word n)) hh
  exact otherRelatorNormalClosure_coordinate_reachable R i hN

end AC
