import AC

/-!
# Andrews--Curtis moves preserve the presented group

The shared conjecture is stated only for tuples that present the trivial group.
This file proves a structural fact connecting that semantic hypothesis to the
move calculus: every primitive AC move preserves the normal closure of the
relators, hence every finite AC path preserves the presented quotient and in
particular preserves `PresentsTrivialGroup`.

The result is rank-independent and uses only the official `AC.Step`
constructors.
-/

namespace AC

/-- The normal closure generated by all relators in a presentation. -/
def relatorNormalClosure {n : ℕ} (R : Relators n) : Subgroup (Word n) :=
  Subgroup.normalClosure (Set.range R)

/-- Every relator lies in the normal closure generated by the tuple. -/
theorem relator_mem_normalClosure {n : ℕ} (R : Relators n) (i : Fin n) :
    R i ∈ relatorNormalClosure R := by
  exact Subgroup.subset_normalClosure ⟨i, rfl⟩

/-- One primitive AC move leaves the normal closure of the relator tuple
unchanged. -/
theorem step_relatorNormalClosure_eq {n : ℕ} {R S : Relators n}
    (h : Step R S) :
    relatorNormalClosure R = relatorNormalClosure S := by
  cases h with
  | inv i =>
      apply le_antisymm
      · apply Subgroup.normalClosure_le_normal
        rintro x ⟨k, rfl⟩
        by_cases hki : k = i
        · subst k
          have hs :
              (R i)⁻¹ ∈
                Subgroup.normalClosure
                  (Set.range (Function.update R i (R i)⁻¹)) :=
            Subgroup.subset_normalClosure ⟨i, by simp⟩
          simpa [relatorNormalClosure] using
            (Subgroup.inv_mem _ hs)
        · exact Subgroup.subset_normalClosure ⟨k, by simp [hki]⟩
      · apply Subgroup.normalClosure_le_normal
        rintro x ⟨k, rfl⟩
        by_cases hki : k = i
        · subst k
          have hr : R i ∈ relatorNormalClosure R :=
            relator_mem_normalClosure R i
          simpa [relatorNormalClosure] using
            (Subgroup.inv_mem _ hr)
        · exact Subgroup.subset_normalClosure ⟨k, by simp [hki]⟩

  | mulRight i j hij =>
      apply le_antisymm
      · apply Subgroup.normalClosure_le_normal
        rintro x ⟨k, rfl⟩
        by_cases hki : k = i
        · subst k
          let N :=
            Subgroup.normalClosure
              (Set.range (Function.update R i (R i * R j)))
          have hi : R i * R j ∈ N :=
            Subgroup.subset_normalClosure ⟨i, by simp [N]⟩
          have hj : R j ∈ N :=
            Subgroup.subset_normalClosure ⟨j, by simp [N, Ne.symm hij]⟩
          have hprod : (R i * R j) * (R j)⁻¹ ∈ N :=
            N.mul_mem hi (N.inv_mem hj)
          simpa [N] using hprod
        · exact Subgroup.subset_normalClosure ⟨k, by simp [hki]⟩
      · apply Subgroup.normalClosure_le_normal
        rintro x ⟨k, rfl⟩
        by_cases hki : k = i
        · subst k
          have hi : R i ∈ relatorNormalClosure R :=
            relator_mem_normalClosure R i
          have hj : R j ∈ relatorNormalClosure R :=
            relator_mem_normalClosure R j
          simpa [relatorNormalClosure] using
            (relatorNormalClosure R).mul_mem hi hj
        · exact Subgroup.subset_normalClosure ⟨k, by simp [hki]⟩

  | conj i w =>
      apply le_antisymm
      · apply Subgroup.normalClosure_le_normal
        rintro x ⟨k, rfl⟩
        by_cases hki : k = i
        · subst k
          let N :=
            Subgroup.normalClosure
              (Set.range (Function.update R i (w * R i * w⁻¹)))
          have hs : w * R i * w⁻¹ ∈ N :=
            Subgroup.subset_normalClosure ⟨i, by simp [N]⟩
          have hback : w⁻¹ * (w * R i * w⁻¹) * (w⁻¹)⁻¹ ∈ N :=
            Subgroup.Normal.conj_mem inferInstance _ hs w⁻¹
          simpa [N, mul_assoc] using hback
        · exact Subgroup.subset_normalClosure ⟨k, by simp [hki]⟩
      · apply Subgroup.normalClosure_le_normal
        rintro x ⟨k, rfl⟩
        by_cases hki : k = i
        · subst k
          have hr : R i ∈ relatorNormalClosure R :=
            relator_mem_normalClosure R i
          have hfwd : w * R i * w⁻¹ ∈ relatorNormalClosure R :=
            Subgroup.Normal.conj_mem inferInstance _ hr w
          simpa [relatorNormalClosure] using hfwd
        · exact Subgroup.subset_normalClosure ⟨k, by simp [hki]⟩

/-- Every finite AC path preserves the relator normal closure. -/
theorem reachable_relatorNormalClosure_eq {n : ℕ} {R S : Relators n}
    (h : Reachable R S) :
    relatorNormalClosure R = relatorNormalClosure S := by
  induction h with
  | refl => rfl
  | tail hprefix hstep ih =>
      exact ih.trans (step_relatorNormalClosure_eq hstep)

/-- AC reachability preserves the property of presenting the trivial group. -/
theorem reachable_preserves_presentsTrivialGroup {n : ℕ} {R S : Relators n}
    (h : Reachable R S) :
    PresentsTrivialGroup R ↔ PresentsTrivialGroup S := by
  have hN := reachable_relatorNormalClosure_eq h
  unfold PresentsTrivialGroup PresentedGroup relatorNormalClosure at *
  rw [hN]
  
end AC
