import FunnelCore
import Mathlib.GroupTheory.Commutator.Basic

/-!
# The commutator layer containing the mined removable twists

For a word `b`, let `N_b` be its normal closure in the ambient free group.
Every factor used by the funnel law,

  b⁻¹ * w * b * w⁻¹,

is the element commutator `⁅b⁻¹,w⁆`, hence lies in
`⁅N_b, ⊤⁆`.

This formally places the empirically discovered quotient inside the classical
higher-commutator / relation-module layer without claiming the converse
generation theorem here.
-/

open scoped commutatorElement

namespace AC

def oneRelatorNormalClosure {n : ℕ} (b : Word n) : Subgroup (Word n) :=
  Subgroup.normalClosure ({b} : Set (Word n))

def twistFactorSet {n : ℕ} (b : Word n) : Set (Word n) :=
  {x | ∃ w : Word n, b⁻¹ * w * b * w⁻¹ = x}

def twistNormalLayer {n : ℕ} (b : Word n) : Subgroup (Word n) :=
  Subgroup.normalClosure (twistFactorSet b)

theorem oneRelator_mem_normalClosure {n : ℕ} (b : Word n) :
    b ∈ oneRelatorNormalClosure b := by
  exact Subgroup.subset_normalClosure (by simp [oneRelatorNormalClosure])

theorem twistFactor_eq_commutator {n : ℕ} (b w : Word n) :
    b⁻¹ * w * b * w⁻¹ = ⁅b⁻¹, w⁆ := by
  rfl

theorem twistFactor_mem_commutatorLayer {n : ℕ} (b w : Word n) :
    b⁻¹ * w * b * w⁻¹ ∈
      ⁅oneRelatorNormalClosure b, (⊤ : Subgroup (Word n))⁆ := by
  have hb : b⁻¹ ∈ oneRelatorNormalClosure b :=
    (oneRelatorNormalClosure b).inv_mem (oneRelator_mem_normalClosure b)
  have hw : w ∈ (⊤ : Subgroup (Word n)) := by simp
  rw [twistFactor_eq_commutator]
  exact Subgroup.commutator_mem_commutator hb hw

/-- The normal subgroup generated by all removable twist factors is contained
in the commutator of the relator's normal closure with the ambient free group.
-/
theorem twistNormalLayer_le_commutatorLayer {n : ℕ} (b : Word n) :
    twistNormalLayer b ≤
      ⁅oneRelatorNormalClosure b, (⊤ : Subgroup (Word n))⁆ := by
  letI : (oneRelatorNormalClosure b).Normal := by
    unfold oneRelatorNormalClosure
    infer_instance
  letI : (⊤ : Subgroup (Word n)).Normal := inferInstance
  unfold twistNormalLayer
  apply Subgroup.normalClosure_le_normal
  intro x hx
  rcases hx with ⟨w, rfl⟩
  exact twistFactor_mem_commutatorLayer b w

end AC
