import TwistCommutatorLayer
import Mathlib.Tactic

namespace AC

/-- Ordinary subgroup generated by the removable twist factors. -/
def twistGeneratedLayer {n : ℕ} (b : Word n) : Subgroup (Word n) :=
  Subgroup.closure (twistFactorSet b)

/-- Conjugating one twist factor produces a product of two twist factors.

This cocycle identity is the reason the ordinary subgroup generated by the
factors is already normal.
-/
theorem conjugate_twistFactor {n : ℕ} (b q w : Word n) :
    q * (b⁻¹ * w * b * w⁻¹) * q⁻¹ =
      (b⁻¹ * q * b * q⁻¹)⁻¹ *
        (b⁻¹ * (q * w) * b * (q * w)⁻¹) := by
  group

/-- The ordinary subgroup generated by all twist factors is normal. -/
theorem twistGeneratedLayer_normal {n : ℕ} (b : Word n) :
    (twistGeneratedLayer b).Normal := by
  constructor
  intro x hx q
  unfold twistGeneratedLayer at hx ⊢
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with ⟨w, rfl⟩
      rw [conjugate_twistFactor]
      exact (Subgroup.closure (twistFactorSet b)).mul_mem
        ((Subgroup.closure (twistFactorSet b)).inv_mem
          (Subgroup.subset_closure ⟨q, rfl⟩))
        (Subgroup.subset_closure ⟨q * w, rfl⟩)
  | one =>
      simp
  | mul x y hx hy ihx ihy =>
      have hmem :=
        (Subgroup.closure (twistFactorSet b)).mul_mem ihx ihy
      convert hmem using 1 <;> group
  | inv x hx ih =>
      have hmem :=
        (Subgroup.closure (twistFactorSet b)).inv_mem ih
      convert hmem using 1 <;> group

/-- Therefore taking a normal closure adds nothing: the twist factors already
generate a normal subgroup. -/
theorem twistGeneratedLayer_eq_twistNormalLayer {n : ℕ} (b : Word n) :
    twistGeneratedLayer b = twistNormalLayer b := by
  apply le_antisymm
  · unfold twistGeneratedLayer twistNormalLayer
    exact Subgroup.closure_le_normalClosure
  · unfold twistNormalLayer
    letI : (twistGeneratedLayer b).Normal :=
      twistGeneratedLayer_normal b
    apply Subgroup.normalClosure_le_normal
    exact Subgroup.subset_closure

/-- The ordinary generated twist layer is contained in the relator commutator
layer. -/
theorem twistGeneratedLayer_le_commutatorLayer {n : ℕ} (b : Word n) :
    twistGeneratedLayer b ≤
      ⁅oneRelatorNormalClosure b, (⊤ : Subgroup (Word n))⁆ := by
  rw [twistGeneratedLayer_eq_twistNormalLayer]
  exact twistNormalLayer_le_commutatorLayer b

end AC
