import TwistGeneratedLayer
import Mathlib.Tactic

namespace AC

def twistFactor {n : ℕ} (b w : Word n) : Word n :=
  b⁻¹ * w * b * w⁻¹

/-- Word-level insertion/removal of one removable twist factor with fixed
source word b. -/
inductive WordTwistStep {n : ℕ} (b : Word n) : Word n → Word n → Prop
  | insert (w a : Word n) :
      WordTwistStep b a (twistFactor b w * a)
  | remove (w a : Word n) :
      WordTwistStep b (twistFactor b w * a) a

def WordTwistReachable {n : ℕ} (b : Word n) : Word n → Word n → Prop :=
  Relation.ReflTransGen (WordTwistStep b)

theorem wordTwistStep_symm {n : ℕ} {b a c : Word n}
    (h : WordTwistStep b a c) :
    WordTwistStep b c a := by
  cases h with
  | insert w a => exact WordTwistStep.remove w a
  | remove w a => exact WordTwistStep.insert w a

theorem wordTwistReachable_symm {n : ℕ} {b a c : Word n}
    (h : WordTwistReachable b a c) :
    WordTwistReachable b c a := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail hprefix hstep ih =>
      exact
        (Relation.ReflTransGen.single (wordTwistStep_symm hstep)).trans ih

/-- One word-level twist step changes the target by left multiplication by an
element of the generated twist layer. -/
theorem wordTwistStep_difference_mem {n : ℕ} {b a c : Word n}
    (h : WordTwistStep b a c) :
    c * a⁻¹ ∈ twistGeneratedLayer b := by
  cases h with
  | insert w a =>
      have hg :
          twistFactor b w ∈ twistGeneratedLayer b := by
        apply Subgroup.subset_closure
        exact ⟨w, rfl⟩
      simpa [twistFactor, mul_assoc] using hg
  | remove w a =>
      have hg :
          twistFactor b w ∈ twistGeneratedLayer b := by
        apply Subgroup.subset_closure
        exact ⟨w, rfl⟩
      have hi := (twistGeneratedLayer b).inv_mem hg
      have heq :
          a * (twistFactor b w * a)⁻¹ =
            (twistFactor b w)⁻¹ := by
        group
      rw [heq]
      exact hi

/-- Every finite word-level twist path changes the target by an element of the
generated twist layer. -/
theorem wordTwistReachable_difference_mem {n : ℕ} {b a c : Word n}
    (h : WordTwistReachable b a c) :
    c * a⁻¹ ∈ twistGeneratedLayer b := by
  induction h with
  | refl =>
      simp
  | tail hprefix hstep ih =>
      have hs := wordTwistStep_difference_mem hstep
      have hm := (twistGeneratedLayer b).mul_mem hs ih
      convert hm using 1 <;> group

/-- Every element of the generated twist layer can be realized by a finite
word-level twist path, uniformly over the starting target word. -/
theorem twistGeneratedLayer_mem_reachable {n : ℕ}
    {b h : Word n} (hh : h ∈ twistGeneratedLayer b) (a : Word n) :
    WordTwistReachable b a (h * a) := by
  unfold twistGeneratedLayer at hh
  induction hh using Subgroup.closure_induction generalizing a with
  | mem x hx =>
      rcases hx with ⟨w, rfl⟩
      exact Relation.ReflTransGen.single (WordTwistStep.insert w a)
  | one =>
      simpa using
        (Relation.ReflTransGen.refl :
          WordTwistReachable b a a)
  | mul x y hx hy ihx ihy =>
      have p1 : WordTwistReachable b a (y * a) := ihy a
      have p2 : WordTwistReachable b (y * a) (x * (y * a)) :=
        ihx (y * a)
      have p := p1.trans p2
      simpa [mul_assoc] using p
  | inv x hx ih =>
      have p :
          WordTwistReachable b (x⁻¹ * a) (x * (x⁻¹ * a)) :=
        ih (x⁻¹ * a)
      have p' : WordTwistReachable b (x⁻¹ * a) a := by
        simpa [mul_assoc] using p
      exact wordTwistReachable_symm p'

/-- Exact fixed-source orbit characterization.

Two target words are connected by finite removable twists with source b iff
their left difference belongs to the subgroup generated by the twist factors.
-/
theorem wordTwistReachable_iff_difference_mem {n : ℕ}
    (b a c : Word n) :
    WordTwistReachable b a c ↔
      c * a⁻¹ ∈ twistGeneratedLayer b := by
  constructor
  · exact wordTwistReachable_difference_mem
  · intro h
    have p := twistGeneratedLayer_mem_reachable h a
    have heq : (c * a⁻¹) * a = c := by group
    rw [heq] at p
    exact p

end AC
