import TwistCommutatorLayer
import Mathlib.Tactic

open scoped commutatorElement

namespace AC

/-- Words whose commutator with every ambient word lies in the twist layer. -/
def centralModuloTwist {n : ℕ} (b : Word n) : Subgroup (Word n) where
  carrier := {a | ∀ g : Word n, ⁅a, g⁆ ∈ twistNormalLayer b}
  one_mem' := by
    intro g
    simp
  mul_mem' := by
    intro a c ha hc g
    letI : (twistNormalLayer b).Normal := by
      unfold twistNormalLayer
      infer_instance
    rw [commutatorElement_mul_left_eq_conj_mul]
    exact (twistNormalLayer b).mul_mem
      (Subgroup.Normal.conj_mem inferInstance _ (hc g) a)
      (ha g)
  inv_mem' := by
    intro a ha g
    letI : (twistNormalLayer b).Normal := by
      unfold twistNormalLayer
      infer_instance
    rw [commutatorElement_inv_left]
    have hga : ⁅g, a⁆ ∈ twistNormalLayer b := by
      have hi := (twistNormalLayer b).inv_mem (ha g)
      rw [commutatorElement_inv] at hi
      exact hi
    exact Subgroup.Normal.conj_mem' inferInstance _ hga a

/-- The central-modulo-twist subgroup is normal. -/
theorem centralModuloTwist_normal {n : ℕ} (b : Word n) :
    (centralModuloTwist b).Normal := by
  constructor
  intro a ha q
  change ∀ g : Word n, ⁅q * a * q⁻¹, g⁆ ∈ twistNormalLayer b
  change ∀ g : Word n, ⁅a, g⁆ ∈ twistNormalLayer b at ha
  intro g
  letI : (twistNormalLayer b).Normal := by
    unfold twistNormalLayer
    infer_instance
  have hbase :
      ⁅a, q⁻¹ * g * q⁆ ∈ twistNormalLayer b :=
    ha (q⁻¹ * g * q)
  have hconj :
      q * ⁅a, q⁻¹ * g * q⁆ * q⁻¹ ∈ twistNormalLayer b :=
    Subgroup.Normal.conj_mem inferInstance _ hbase q
  rw [conjugate_commutatorElement] at hconj
  simpa [mul_assoc] using hconj

/-- The distinguished generator b is central modulo its twist layer. -/
theorem generator_mem_centralModuloTwist {n : ℕ} (b : Word n) :
    b ∈ centralModuloTwist b := by
  change ∀ g : Word n, ⁅b, g⁆ ∈ twistNormalLayer b
  intro g
  letI : (twistNormalLayer b).Normal := by
    unfold twistNormalLayer
    infer_instance
  have hdelta :
      b⁻¹ * g * b * g⁻¹ ∈ twistNormalLayer b := by
    apply Subgroup.subset_normalClosure
    exact ⟨g, rfl⟩
  have hbinv : ⁅b⁻¹, g⁆ ∈ twistNormalLayer b := by
    rw [← twistFactor_eq_commutator]
    exact hdelta
  have hgb : ⁅g, b⁆ ∈ twistNormalLayer b := by
    have hc :
        b * ⁅b⁻¹, g⁆ * b⁻¹ ∈ twistNormalLayer b :=
      Subgroup.Normal.conj_mem inferInstance _ hbinv b
    rw [commutatorElement_inv_left] at hc
    simpa [mul_assoc] using hc
  have hi := (twistNormalLayer b).inv_mem hgb
  rw [commutatorElement_inv] at hi
  exact hi

/-- The normal closure of b is central modulo the twist layer. -/
theorem oneRelatorNormalClosure_le_centralModuloTwist {n : ℕ} (b : Word n) :
    oneRelatorNormalClosure b ≤ centralModuloTwist b := by
  letI : (centralModuloTwist b).Normal :=
    centralModuloTwist_normal b
  unfold oneRelatorNormalClosure
  apply Subgroup.normalClosure_le_normal
  intro x hx
  have hxb : x = b := by
    simpa using hx
  subst x
  exact generator_mem_centralModuloTwist b

/-- Reverse inclusion: the full commutator layer is generated by removable
conjugacy-difference twists. -/
theorem commutatorLayer_le_twistNormalLayer {n : ℕ} (b : Word n) :
    ⁅oneRelatorNormalClosure b, (⊤ : Subgroup (Word n))⁆ ≤
      twistNormalLayer b := by
  rw [Subgroup.commutator_le]
  intro a ha g _hg
  have hcentral :=
    oneRelatorNormalClosure_le_centralModuloTwist b ha
  change ∀ x : Word n, ⁅a, x⁆ ∈ twistNormalLayer b at hcentral
  exact hcentral g

/-- Exact characterization of the layer discovered by theorem mining.

The normal subgroup generated by all removable factors
  b⁻¹ w b w⁻¹
is precisely the commutator of the normal closure of b with the ambient free
group.
-/
theorem twistNormalLayer_eq_commutatorLayer {n : ℕ} (b : Word n) :
    twistNormalLayer b =
      ⁅oneRelatorNormalClosure b, (⊤ : Subgroup (Word n))⁆ := by
  apply le_antisymm
  · exact twistNormalLayer_le_commutatorLayer b
  · exact commutatorLayer_le_twistNormalLayer b

end AC
