#!/usr/bin/env python3
from pathlib import Path
src=Path('scripts/run_developmental_distinction_discovery_v15.py')
dst=Path('scripts/run_developmental_distinction_invention_v19.py')
s=src.read_text()
s=s.replace('developmental-distinction-discovery-v15','developmental-distinction-invention-v19')
s=s.replace('fault-v15-','fault-v19-')
s=s.replace("FEATURES=['event_count_bucket','has_false_result','last_depth_bucket','last_kind','last_module','last_site','semantic_site_count']", "FEATURES=['last_depth_bucket','depth_span_bucket','terminal_depth_role','terminal_depth_repeat','depth_turn_bucket','depth_distinct_bucket','first_last_depth_relation']")
s=s.replace("'last_kind':last.get('kind','NONE'),", "'last_kind':'MATCHED_KIND',\n      'raw_last_kind':last.get('kind','NONE'),")
s=s.replace("'last_module':last.get('site','NONE').split('.',1)[0] if last.get('site') else 'NONE',", "'last_module':'MATCHED_MODULE',\n      'raw_last_module':last.get('site','NONE').split('.',1)[0] if last.get('site') else 'NONE',")
s=s.replace("'last_site':last.get('site','NONE'),", "'last_site':'MATCHED_SITE',\n      'raw_last_site':last.get('site','NONE'),")
s=s.replace("'semantic_site_count':str(len(sites)),", "'semantic_site_count':'MATCHED_SITE_COUNT',\n      'raw_semantic_site_count':str(len(sites)),\n      'depth_span_bucket': depth_span_bucket,\n      'terminal_depth_role': terminal_depth_role,\n      'terminal_depth_repeat': terminal_depth_repeat,\n      'depth_turn_bucket': depth_turn_bucket,\n      'depth_distinct_bucket': depth_distinct_bucket,\n      'first_last_depth_relation': first_last_depth_relation,")
needle="""    try: d=int(depth) if depth is not None else -1\n    except: d=-1\n    return {\n"""
insert="""    try: d=int(depth) if depth is not None else -1\n    except: d=-1\n    depths=[]\n    for e in ev:\n        try:\n            if e.get('depth') is not None: depths.append(int(e.get('depth')))\n        except: pass\n    if depths:\n        span=max(depths)-min(depths)\n        depth_span_bucket='0' if span==0 else ('1' if span==1 else ('2_3' if span<=3 else 'ge4'))\n        lastd=depths[-1]\n        if min(depths)==max(depths): terminal_depth_role='flat'\n        elif lastd==min(depths): terminal_depth_role='min'\n        elif lastd==max(depths): terminal_depth_role='max'\n        else: terminal_depth_role='interior'\n        terminal_depth_repeat='yes' if lastd in depths[:-1] else 'no'\n        signs=[]\n        for a,b in zip(depths,depths[1:]):\n            if b>a: signs.append(1)\n            elif b<a: signs.append(-1)\n        turns=sum(1 for a,b in zip(signs,signs[1:]) if a!=b)\n        depth_turn_bucket='0' if turns==0 else ('1' if turns==1 else 'ge2')\n        distinct=len(set(depths)); depth_distinct_bucket='1' if distinct==1 else ('2' if distinct==2 else 'ge3')\n        first_last_depth_relation='same' if depths[0]==lastd else ('up' if lastd>depths[0] else 'down')\n    else:\n        depth_span_bucket=terminal_depth_role=terminal_depth_repeat=depth_turn_bucket=depth_distinct_bucket=first_last_depth_relation='NONE'\n    return {\n"""
if needle not in s: raise SystemExit('V19 depth invention anchor missing')
s=s.replace(needle,insert,1)
s=s.replace("if {r['features']['event_count_bucket'] for r in rows}!={'MATCHED'}: raise SystemExit('event-count matching intervention failed')", "if {r['features']['event_count_bucket'] for r in rows}!={'MATCHED'}: raise SystemExit('event-count matching intervention failed')\nif {r['features']['last_kind'] for r in rows}!={'MATCHED_KIND'}: raise SystemExit('last-kind matching intervention failed')\nif {r['features']['last_module'] for r in rows}!={'MATCHED_MODULE'}: raise SystemExit('last-module matching intervention failed')\nif {r['features']['last_site'] for r in rows}!={'MATCHED_SITE'}: raise SystemExit('last-site matching intervention failed')\nif {r['features']['semantic_site_count'] for r in rows}!={'MATCHED_SITE_COUNT'}: raise SystemExit('site-count matching intervention failed')")
s=s.replace("'destroyed_shortcut':'event_count_bucket',", "'destroyed_feature_family':['event_count_bucket','last_kind','last_module','last_site','semantic_site_count'],'invented_relational_family':['depth_span_bucket','terminal_depth_role','terminal_depth_repeat','depth_turn_bucket','depth_distinct_bucket','first_last_depth_relation'],")
s=s.replace("'status':'LIVE_SHORTCUT_DESTROYED_DISTINCTION_V15'", "'status':'LIVE_RELATIONAL_DISTINCTION_INVENTION_V19'")
s=s.replace("if 'event_count_bucket' in selected_features: raise SystemExit('destroyed shortcut was selected')", "if any(f in selected_features for f in ['event_count_bucket','last_kind','last_module','last_site','semantic_site_count']): raise SystemExit('destroyed feature family was selected')")
s=s.replace("if train_error!=0: raise SystemExit('split phase failed after shortcut destruction')", "if train_error!=0: raise SystemExit('invented relational vocabulary did not close V18 obstruction')")
s=s.replace("if hold_acc!=1.0: raise SystemExit('learned quotient failed source-distinct transfer after shortcut destruction')", "if hold_acc!=1.0: raise SystemExit('invented relational quotient failed source-distinct transfer')")
dst.write_text(s)
print('generated V19 relational-depth invention after V18 obstruction')
