name: ACC Competitive Residual Scheduler

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  cycle:
    uses: heathsanchez/test/.github/workflows/acc-competitive-residual-v1.yml@acc-competitive-residual-v1
    secrets: inherit
